#!/usr/bin/env python3
"""Watch SITES_DIR and regenerate Caddy virtual-host routes for static sites.

Configure via environment variables:
  SITES_DIR      - directory to watch (default: /sites)
  SITES_DOMAIN   - base domain for subdomains (default: example.com)
  OUTPUT_FILE    - output Caddyfile path (default: /out/extra-sites.caddy)
  CADDY_CONTAINER - Docker container name to reload (default:?? UST-string-caddy)
  SITES_BACKEND  - upstream Docker service name (default: sites-backend)
"""

from __future__ import annotations

import logging
import os
import re
import subprocess
import threading
import time
from pathlib import Path

SITES_DIR = Path(os.environ.get("SITES_DIR", "/sites"))
SITES_DOMAIN = os.environ.get("SITES_DOMAIN", "example.com")
OUTPUT = Path(os.environ.get("OUTPUT_FILE", "/out/extra-sites.caddy"))
CADDY_CONTAINER = os.environ.get("CADDY_CONTAINER", "ust-caddy")
SITES_BACKEND = os.environ.get("SITES_BACKEND", "sites-backend")
SITE_RE = re.compile(r"^[a-zA-Z0-9_-]+$")
SKIP_DIRS: frozenset[str] = frozenset({"ust"})

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger("caddy-sites-watcher")


def list_site_domains() -> list[str]:
    if not SITES_DIR.is_dir():
        return []
    domains: list[str] = []
    for entry in sorted(SITES_DIR.iterdir(), key=lambda p: p.name.lower()):
        if not entry.is_dir():
            continue
        name = entry.name
        if name in SKIP_DIRS or not SITE_RE.match(name):
            continue
        domains.append(f"{name}.{SITES_DOMAIN}")
    return domains


def render_caddy(domains: list[str]) -> str:
    if not domains:
        return "# AUTOGENERATED — no static sites found\n"

    hosts = ", ".join(domains)
    lines = [
        "# AUTOGENERATED by caddy_sites_watcher.py — do not edit",
        f"{hosts} {{",
        "\tencode gzip",
        f"\treverse_proxy {SITES_BACKEND}:8080 {{",
        "\t\theader_up Host {host}",
        "\t\theader_up X-Real-IP {remote_host}",
        "\t\theader_up X-Forwarded-For {remote_host}",
        "\t\theader_up X-Forwarded-Proto {scheme}",
        "\t}",
        "}",
        "",
    ]
    return "\n".join(lines)


def reload_caddy() -> None:
    result = subprocess.run(
        ["docker", "exec", CADDY_CONTAINER, "caddy", "reload", "--config", "/etc/caddy/Caddyfile"],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        log.error("caddy reload failed: %s", result.stderr.strip() or result.stdout.strip())
    else:
        log.info("caddy reloaded")


def write_and_reload(force: bool = False) -> None:
    domains = list_site_domains()
    content = render_caddy(domains)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)

    if not force and OUTPUT.exists() and OUTPUT.read_text(encoding="utf-8") == content:
        return

    OUTPUT.write_text(content, encoding="utf-8")
    log.info("updated %s (%d sites)", OUTPUT.name, len(domains))
    reload_caddy()


class SitesHandler:
    def __init__(self, sites_dir: Path) -> None:
        self.sites_dir = sites_dir.resolve()
        self._timer: threading.Timer | None = None
        self._lock = threading.Lock()

    def _schedule(self) -> None:
        with self._lock:
            if self._timer:
                self._timer.cancel()
            self._timer = threading.Timer(2.0, write_and_reload)
            self._timer.daemon = True
            self._timer.start()

    def _is_tracked_top_level(self, path: str) -> bool:
        p = Path(path).resolve()
        return (
            p.parent == self.sites_dir
            and p.name not in SKIP_DIRS
            and SITE_RE.match(p.name) is not None
        )


def main() -> None:
    try:
        from watchdog.events import FileSystemEvent, FileSystemEventHandler
        from watchdog.observers.polling import PollingObserver
    except ImportError:
        log.error("watchdog not installed — run: pip install watchdog")
        raise

    handler_obj = SitesHandler(SITES_DIR)

    class _Handler(FileSystemEventHandler):
        def on_created(self, event: FileSystemEvent) -> None:
            if event.is_directory and handler_obj._is_tracked_top_level(event.src_path):
                log.info("new site folder: %s", Path(event.src_path).name)
                handler_obj._schedule()

        def on_deleted(self, event: FileSystemEvent) -> None:
            if event.is_directory and handler_obj._is_tracked_top_level(event.src_path):
                log.info("removed site folder: %s", Path(event.src_path).name)
                handler_obj._schedule()

        def on_moved(self, event: FileSystemEvent) -> None:
            src = event.is_directory and handler_obj._is_tracked_top_level(event.src_path)
            dst = event.is_directory and handler_obj._is_tracked_top_level(event.dest_path)
            if src or dst:
                log.info("site folder renamed: %s → %s",
                         Path(event.src_path).name, Path(event.dest_path).name)
                handler_obj._schedule()

    log.info("watching %s (domain: *.%s)", SITES_DIR, SITES_DOMAIN)
    write_and_reload(force=True)

    observer = PollingObserver(timeout=3)
    observer.schedule(_Handler(), str(SITES_DIR), recursive=True)
    observer.start()

    try:
        while True:
            time.sleep(30)
            write_and_reload()
    except KeyboardInterrupt:
        observer.stop()
    observer.join()


if __name__ == "__main__":
    main()
